# -*- coding: utf-8 -*-
"""Alpro Pertemuan KE-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lrt5SPDzlIAEFnimfLCdUPlU0PhAihK

Tupels dan set
"""

# list

data_list = [10,2,4,5,6]
print(f"list : {data_list}")
print(f"list pertama : {data_list[0]}\n")

# tupels -> kurung () -> kurung biasa
data_tupels = (7,2,4,5,8,9)
print(f"tupels : {data_tupels}")
print(f"tupels pertama : {data_tupels[0]}\n")

# data_tupels.pop()
# print(f"tupels setelah ditambah {data_tupels}")

# set
data_sets = {13,7,8,4,5,6,9} #himpunan
print(f" sets : {data_sets}")

"""Dictionary"""

# list -> array untuk mengakses data membutuhkan index -> identifier
data_list = ['ucup','bahlil','xin think']
print(f"data indek ke 1 : {data_list[1]}\n")

# dictionary (dict) -> array asosiatif
# identifie -> key

data_dict = {
    'key':'value',
    'cp':'ucup',
    'bhl':'bahlil',
    'xin':'xin think',
    'nmbr': 100,
    'list':data_list,
}
print(data_dict)
print(data_dict["list"])

"""Operasi Dictionary"""

data_dict = {
    'cup':'ucup cupcup',
    'pet':'peot sureot',
    'lil':'gumil sihulil',
}

# panjang / jumlah data dict
dict_len = len(data_dict)
print(dict_len)

# mengecek key yang tersedia atau tidak
key = "pet"
check_key = key in data_dict
print(check_key)

# mengakses read data dengan get
# print(data_dict["cup"])
# print(data_dict.get("cup"))
# print(data_dict.get("xin","key tersebut tidak ada"))

# mengubah data
print(f"data sebelum di ubah : {data_dict}\n")
data_dict['lil'] = "bahlil goblin"
#print(f"setelah di ubah : {data_dict}")

data_dict['xin'] = "xin thambah"
print(f"setelah di ubah : {data_dict}\n")

data_dict.update({"xin":"xinta"})
print(f"setelah di ubah : {data_dict}\n")

# menghapus data
del data_dict["lil"]
print(f"setelah di ubah : {data_dict}\n")

"""Looping dictionary"""

nakama = {
    'hin':'hinata',
    'tay':'saitama',
    'nob':'nobita',
    'fhm':'king glory',
}

# for rakyat in nakama:
#   print(rakyat)

demon_god = nakama.keys()
print(demon_god)

for key in nakama.keys():
  print(f"key nya adalah: {key}")

# mengambil value
nilai = nakama.values()
print(nilai)

# lakukan perulangan untuk mengambil nilainya saja
for demon in nakama.values():
  print(f"nilai nya adalah : {demon}")

all = nakama.items()
print(all)

# dikeluarkan menggunakan perulangan
for demon in nakama.items():
  print(f"semua item nya adalah : {demon}")

for key,value in nakama.items():
  print(f"key = {key} -> value = {value}")